services:
  fitcoder:
    build:
      context: .
    stdin_open: true
    tty: true

  fitcoder-gui:
    build:
      context: .
    profiles:
      - gui
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
